<template>
  <div class="p-16">
    <h1 class="font-bold text-xl mb-5">Über dieses Projekt</h1>
    <p class="inline-block py-3">Scigate ist ein Showcase und One-Stop-Shop für (Rechts-)Daten. Zurzeit handelt es sich bei scigate um einen frühen Prototypen.</p>
    <h2 class="font-bold text-lg">I. Datenhunger</h2>
    <p class="inline-block py-3">Künstliche Intelligenz braucht Daten, natürliche Intelligenz auch. Gateway zu diesen Daten im weitesten Sinne war früher, nicht zuletzt wenn es um die Wissenschaft ging, vor allem die Bibliothek. Gatekeeper zu diesen Daten waren die Bibliothekarinnen und Bibliothekare, welche die Texte, die Daten mit Metadaten versahen und sie so such- und auffindbar machten.</p>
    <p class="inline-block py-3">Von dieser Bibliothek ist heute wenig geblieben. Wissenschaftsdaten werden heute häufig in Datenbanken verschiedenster Akteure zur Verfügung gestellt, mit unterschiedlichem Zugang und verschiedenster Zugänglichkeit, nicht zuletzt in Hinblick auf die inhaltliche Erschliessung und so auch wiederum Such- und Auffindbarkeit der Daten. Eine bedeutende Rolle nehmen Grossverlage ein, die mit ihren Datenbanken die öffentlichen Bibliotheken als Gatekeeper des Wissens weitestgehend abgelöst haben.</p>
    <p class="inline-block py-3">Diese Fragmentierung des Zugangs zu Wissenschaftsdaten beeinträchtigt die nationale und internationale Forschung und deren Sichtbarkeit. Das Projekt scigate möchte versuchen, hier einen Gegenpol zu bilden. Jenseits der weiterhin bestehenden und zudem wünschenswerten Vielfalt der Datenquellen soll ein einheitlicher Sucheinstieg in die heute stark fragmentiere Landschaft wissenschaftlicher Datenbanken sowie ein niederschwellig zugänglicher One-Stop-Shop für Wissenschaftsdaten geschaffen werden. </p>
    <h2 class="font-bold text-lg">II. Showcase und One-Stop-Shop für (Rechts-)Daten</h2>
    <p class="inline-block py-3">Mit scigate haben wir einen ersten Prototypen geschaffen, mit dem Schwerpunkt rechtswissenschaftliche Daten: Wäre es nicht schön, von einem Ort aus das ganze Textkorpus „Recht“ durchsuchen zu können – alle Rechtsdaten, Gesetze, wissenschaftliche Veröffentlichungen, Urteile und sonstige Texte aus der sogenannten Rechtspraxis? Und wäre es nicht mindestens ebenso schön, auf all diese Rechtstexte dann auch sogleich zugreifen zu können?</p>
    <p class="inline-block py-3">Mit scigate soll eine solche Schnittstelle zum Textkorpus Recht skizziert werden, die klassische Suchschnittstelle und moderne Programmierschnittstelle zugleich ist. </p>
    <p class="inline-block py-3">scigate ist, wenn überhaupt, ein „running prototype“, ein Konzept, das hoffentlich nicht zu langweilig ist, um diskutiert zu werden. Die Herausforderungen sind gross, doch die damit verbundene Möglichkeiten zu verlockend.</p>
    <p class="inline-block py-3">Zur Reduzierung der Komplexität wird eine weitgehende Modularisierung von scigate angestrebt. So erfolgt insbesondere die Datenaggregierung weiter an verschiedensten Orten, in verschiedensten Formaten und Datenbanken. Dreh- und Angelpunkt von scigate werden damit sogenannte Plug-Ins, deren Aufgabe es ist, Datenquellen anzusprechen und ihre Antwort zurück für scigate zu übersetzen.</p>
    <p class="inline-block py-3">Wie aber werden dann etwa die Suchergebnisse dargestellt? Kann man diese so heterogenen Suchergebnisse in einer Liste zusammenführen? Inwieweit müssen wir die Daten der einzelnen Datenquellen homogenisieren, um sie dann auch homogen abrufen zu können? Wie gehen wir mit Dubletten um? Wie gewichtet man die Ergebnisse? Legt man die Gewichtung offen? Soll man dann gar zwischen verschiedensten offenen Gewichtungen und Suchalgorhythmen wählen können? Hilft eine graphische Aufarbeitung der Suchergebnisse? Und wie steht man zur Künstlichen Intelligenz, als Abbild dieses so bereits geschaffenen Wissens und als vielleicht Motor künftiger Wissenschaft? Eine Lösung für alles auf einmal wird man kaum finden. Aber auf zweimal, dreimal, Stück für Stück und modular. Vielleicht.</p>
  </div>
</template>